### ISSUE TITLE
Crear proyecto base

### ISSUE THREAD

**Issue by lemartinezm** [Open-Bootcamp/movie-app#1]
Tener en cuenta:

   - [x] Definir tecnologías (React + Material UI + CSS)
   - [x] Realizar configuraciones iniciales (eslint, prettier, etc)
   - [x] Crear rama develop a partir de master
   - [x] Crear la documentación inicial para que cualquiera pueda iniciar el proyecto de manera local

**Comment by MaxC0d3** [comment]
Completed
