### ISSUE TITLE
Maquetar la página favoritos

### ISSUE THREAD

**Issue by lemartinezm** [Open-Bootcamp/movie-app#10]
El usuario puede:

- [x] Ver las películas y series que guardó en favoritos.
- [x] Quitar de favoritos las películas o series que se muestran
- [x] Ver una imagen que indique que no tiene favoritos si no guardó alguno previamente.

Tener en cuenta:

- [x] Diseño responsive.
- [x] Gestión de estados al quitar una serie o película de favoritos.

**Comment by JoseCaicedoDev** [comment]
Logica de favorite y not found
