### ISSUE TITLE
Crear el enrutado de la aplicación

### ISSUE THREAD

**Issue by lemartinezm** [Open-Bootcamp/movie-app#2]
La aplicación debe tener las rutas:

   - [x] Home
   - [x] Search
   - [x] Favourites

   Tener en cuenta:

   - [x] Crear el componente correspondiente a la página.
   - [x] Renderizar estos componentes en las rutas.

**Comment by JoseCaicedoDev** [comment]
Completado

**Comment by lemartinezm** [comment]
Correcto
