### ISSUE TITLE
Maquetar la barra de navegación

### ISSUE THREAD

**Issue by lemartinezm** [Open-Bootcamp/movie-app#3]
El usuario puede:

   - [x] Navegar entre las secciones correspondientes.
   - [x] Buscar una película o serie utilizando la barra de búsquedas. Al dar enter (o al botón en caso de mobile) debe redirigir a una página con los resultados encontrados

   Tener en cuenta:

   - [x] Diseño responsive.

**Comment by MaxC0d3** [comment]
Checked.

**Comment by MaxC0d3** [comment]
Lógica de búsqueda, fix de boton buscar, responsive desing
