### ISSUE TITLE
Maquetar la sección de películas de la página principal y ruta individual

### ISSUE THREAD

**Issue by lemartinezm** [Open-Bootcamp/movie-app#8]
El usuario puede:

   - [x] Ver las películas disponibles.
   - [x] Arrastrar para ver el contenido completo (si fuesen demasiados elementos).
   - [x] Añadir o quitar de favoritos películas

   Tener en cuenta:

   - [x] Diseño responsive.
   - [x] Reutilización de componentes.
   - [x] Gestión del estado al guardar o quitar una película de favoritos.

**Comment by MaxC0d3** [comment]
Completado
