### ISSUE TITLE
Maquetar la sección de series de la página principal y ruta individual

### ISSUE THREAD

**Issue by lemartinezm** [Open-Bootcamp/movie-app#9]
El usuario puede:

   - [x] Ver las series disponibles.
   - [x] Arrastrar para ver el contenido completo (si fuesen demasiados elementos).
   - [x] Añadir o quitar de favoritos series

   Tener en cuenta:

   - [x] Diseño responsive.
   - [x] Reutilización de componentes.
   - [x] Gestión del estado al guardar o quitar una serie de favoritos.

**Comment by MaxC0d3** [comment]
Completado
